pasta/pasta/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('accounts.urls')),
    path('recipes/', include('recipes.urls')),
    path('wiki/', include('wiki.urls')),
    path('search/', include('search.urls')),
]

# Используйте static() чтобы добавить соотношения для статических файлов
# Только на период разработки
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pasta/recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.RecipeListView.as_view(), name='recipe-list'),
    path('create/', views.recipe_create_form, name='recipe-create'),
    path('show/<slug:slug>', views.RecipeDetailView.as_view(), name='recipe-detail'),
    path('edit/<slug:slug>', views.recipe_edit_form, name='recipe-edit'),
    path('remove/<slug:slug>', views.RecipeDeleteView.as_view(), name='recipe-remove'),
    path('publish/<slug:slug>', views.change_recipe_publish, name='recipe-publish'),
]

pasta/wiki/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='wiki'),
    path('ingredients/', views.IngredientGroupListView.as_view(), name='ingredient-groups-list'),
    path('ingredients/<slug:group_slug>/', views.IngredientListView.as_view(), name='group-ingredients-list'),
    path('ingredients/<slug:group_slug>/<slug:slug>', views.IngredientDetailView.as_view(), name='ingredient-detail'),
    path('instruments/', views.InstrumentListView.as_view(), name='instruments-list'),
    path('instruments/<slug:slug>/', views.InstrumentDetailView.as_view(), name='instrument-detail'),
]

pasta/recipes/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from utils.func import unique_slugify
from pytils.translit import slugify

class Cuisine(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')

    class Meta:
        verbose_name = 'Кухня'
        verbose_name_plural = 'Кухни'

    def __str__(self):
        return self.name


class Menu(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=50, verbose_name='Наименование')
    slug = models.SlugField(max_length=70, unique=True, blank=True, null=False, help_text='Заполняется автоматически.')
    cuisine = models.ForeignKey('Cuisine', on_delete=models.SET_NULL, null=True, verbose_name='Кухня')
    menu = models.ForeignKey('Menu', on_delete=models.SET_NULL, null=True, verbose_name='Меню')
    cooking_time = models.TimeField(null=True, verbose_name='Время приготовления')
    image = models.ImageField(upload_to='recipes/recipe/', verbose_name='Фотография готового блюда')
    description = models.TextField(max_length=1000, verbose_name='Описание блюда')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, verbose_name='Автор')
    is_published = models.BooleanField(blank=True, default=0, verbose_name='Опубликован')
    creation_date = models.DateField(verbose_name='Дата создания', auto_now_add=True, blank=True, editable=False)

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug or not self.slug.startswith(slugify(self.title)):
            self.slug = unique_slugify(self)
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('recipe-detail', kwargs={'slug':self.slug})


class AmoutUnit(models.Model):
    name = models.CharField(max_length=20, verbose_name='Наименование')
    need_amount = models.BooleanField(
        default=1,
        verbose_name='Количественная',
        help_text='Установите флажок, если мерной единице требуется указание какой-либо количественной суммы. '
                  'Например, для мерной ед. "по вкусу" указание суммы не требуется.'
    )

    class Meta:
        verbose_name = 'Мерная единица'
        verbose_name_plural = 'Мерные единицы'

    def __str__(self):
        return self.name


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey('wiki.Ingredient', on_delete=models.DO_NOTHING, verbose_name='Ингредиент')
    amount = models.IntegerField(blank=True, null=True, verbose_name='Сумма')
    unit = models.ForeignKey('AmoutUnit', on_delete=models.DO_NOTHING, verbose_name='Мерная единица')
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE, blank=True, verbose_name='Рецепт')

    class Meta:
        verbose_name = 'Ингредиент (рецепты)'
        verbose_name_plural = 'Ингредиенты (рецепты)'

    def __str__(self):
        return f'{self.ingredient.name}: {self.recipe.title}'
    
    def get_absolute_url(self):
        return reverse('recipe-detail', kwargs={'slug':self.recipe.slug})


class RecipeStep(models.Model):
    image = models.ImageField(upload_to='recipes/recipesteps/', verbose_name='Иллюстрация')
    description = models.TextField(max_length=5000, verbose_name='Описание')
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE, blank=True, verbose_name='Рецепт')

    class Meta:
        verbose_name = 'Шаг'
        verbose_name_plural = 'Шаги'
    
    def get_absolute_url(self):
        return reverse('recipe-detail', kwargs={'slug':self.recipe.slug})

pasta/recipes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponseRedirect
from django.http.request import HttpRequest
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Recipe, RecipeIngredient, RecipeStep
from .forms import RecipeFilterForm, RecipeModelForm, RecipeIngredientModelForm, RecipeStepModelForm, BaseRecipeIngredientFormSet, BaseRecipeStepFormSet, BaseRecipeIngredientModelFormSet, BaseRecipeStepModelFormSet
from django.forms import formset_factory, modelformset_factory
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic.edit import DeleteView
from django.contrib import messages


COOKING_TIME_INITIAL_DATA = '01:00'

class RecipeBaseListView(generic.ListView):
    model = Recipe

    def get_queryset(self):
        queryset = Recipe.objects.select_related('author', 'menu', 'cuisine')
        return queryset
    
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            favorites = self.request.user.favorites.all()
            context_data['favorites'] = favorites
        return context_data


class RecipeListView(RecipeBaseListView):
    paginate_by = 10
    
    def get_queryset(self):
        queryset = super().get_queryset().filter(is_published=1)
        if queryset.exists():
            if self.request.GET:
                form = RecipeFilterForm(self.request.GET)
                if form.is_valid():
                    menu = form.cleaned_data.get('menu')
                    cuisine = form.cleaned_data.get('cuisine')
                    if menu:
                        queryset = queryset.filter(menu=menu)
                    if cuisine:
                        queryset = queryset.filter(cuisine=cuisine)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        menu = self.request.GET.get('menu', 0)
        cuisine = self.request.GET.get('cuisine', 0)
        context_data['form'] = RecipeFilterForm(initial={'menu': menu, 'cuisine': cuisine})
        return context_data


class RecipeDetailView(generic.DetailView):
    model = Recipe

    def get_object(self):
        recipe = Recipe.objects.select_related('cuisine', 'menu', 'author').prefetch_related('recipeingredient_set__ingredient', 'recipeingredient_set__ingredient__group', 'recipeingredient_set__unit','recipestep_set').filter(slug=self.kwargs.get('slug'))
        if not recipe.exists():
            raise Http404
        recipe = recipe.first()
        if not recipe.is_published and recipe.author != self.request.user:
            raise Http404
        return recipe
    
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            favorites = self.request.user.favorites.all()
            context_data['favorites'] = favorites
        return context_data


@login_required
def recipe_create_form(request: HttpRequest):
    if not request.user.is_confirmed:
        from accounts.views import send_activation_message
        return send_activation_message(request)
    if not request.user.has_filled_initials():
        messages.error(
            request, 
            'Пожалуйста, заполните поля ниже для возможности создания рецептов!'
        )
        return HttpResponseRedirect(f'{reverse("change-personal-info")}?next=/recipes/create/')

    RecipeIngredientFormSet = formset_factory(
        RecipeIngredientModelForm,
        formset=BaseRecipeIngredientFormSet,
        absolute_max=30,
        max_num=30,
        validate_max=True,
        can_delete=True,
    )
    RecipeStepFormSet = formset_factory(
        RecipeStepModelForm,
        formset=BaseRecipeStepFormSet,
        absolute_max=30,
        max_num=30,
        validate_max=True,
        can_delete=True,
    )

    if request.method == 'POST':

        recipe_form = RecipeModelForm(request.POST, request.FILES, prefix='recipe')
        ingredient_formset = RecipeIngredientFormSet(request.POST, prefix='ingredient')
        step_formset = RecipeStepFormSet(request.POST, request.FILES, prefix='step')
        
        if recipe_form.is_valid() and ingredient_formset.is_valid() and step_formset.is_valid():
            
            recipe = recipe_form.save(commit=False)
            recipe.author = request.user
            if request.POST.get('submit-publish'):
                recipe.is_published = 1
            recipe.save()

            ingredient_formset.clear_and_save(recipe=recipe)
            step_formset.clear_and_save(recipe=recipe)

            return HttpResponseRedirect(reverse('recipe-detail', kwargs={'slug': recipe.slug}))
    else:
        recipe_form = RecipeModelForm(prefix='recipe', initial={'cooking_time': COOKING_TIME_INITIAL_DATA})
        ingredient_formset = RecipeIngredientFormSet(prefix='ingredient')
        step_formset = RecipeStepFormSet(prefix='step')
    
    return render(
        request,
        'recipes/recipe_form.html',
        {
            'recipe_form': recipe_form, 
            'ingredient_formset': ingredient_formset, 
            'step_formset': step_formset
        }
    )


@login_required
def recipe_edit_form(request: HttpRequest, slug):
    RecipeIngredientFormSet = modelformset_factory(
        RecipeIngredient,
        RecipeIngredientModelForm,
        formset=BaseRecipeIngredientModelFormSet,
        absolute_max=30,
        max_num=30,
        validate_max=True,
        can_delete=True,
    )
    RecipeStepFormSet = modelformset_factory(
        RecipeStep,
        RecipeStepModelForm,
        formset=BaseRecipeStepModelFormSet,
        absolute_max=30,
        max_num=30,
        validate_max=True,
        can_delete=True,
    )
    recipe = get_object_or_404(Recipe, slug=slug)
    ingredient_queryset = RecipeIngredient.objects.filter(recipe=recipe.id)
    step_queryset = RecipeStep.objects.filter(recipe=recipe.id)

    if request.method == 'POST':

        recipe_form = RecipeModelForm(request.POST, request.FILES, instance=recipe, prefix='recipe')
        ingredient_formset = RecipeIngredientFormSet(request.POST, queryset=ingredient_queryset, prefix='ingredient')
        step_formset = RecipeStepFormSet(request.POST, request.FILES, queryset=step_queryset, prefix='step')
        
        if recipe_form.is_valid() and ingredient_formset.is_valid() and step_formset.is_valid():
            
            recipe = recipe_form.save(commit=False)
            if request.POST.get('submit-publish'):
                recipe.is_published = 1
            else:
                recipe.is_published = 0
            recipe.save()

            ingredient_formset.clear_and_save(recipe=recipe)
            step_formset.clear_and_save(recipe=recipe)

            return HttpResponseRedirect(reverse('recipe-detail', kwargs={'slug': recipe.slug}))
    else:
        recipe_form = RecipeModelForm(instance=recipe, prefix='recipe')
        ingredient_formset = RecipeIngredientFormSet(queryset=ingredient_queryset, prefix='ingredient')
        step_formset = RecipeStepFormSet(queryset=step_queryset, prefix='step')
    
    return render(
        request,
        'recipes/recipe_form.html',
        {
            'recipe_form': recipe_form, 
            'ingredient_formset': ingredient_formset, 
            'step_formset': step_formset
        }
    )


class RecipeDeleteView(DeleteView):
    model = Recipe
    success_url = reverse_lazy('recipe-list')


@login_required
def change_recipe_publish(request: HttpRequest, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    if not recipe.author == request.user:
        raise Http404
    if recipe.is_published:
        recipe.is_published = False
        messages.success(request, 'Рецепт успешно снят с публикации!')
    else:
        recipe.is_published = True
        messages.success(request, 'Рецепт успешно опубликован!')
    recipe.save()
    return HttpResponseRedirect(reverse('recipe-detail', kwargs={'slug': slug}))

pasta/recipes/templates/recipes/recipe_confirm_delete.html
{% extends "base_generic.html" %}

{% block title %}<title>Паста | Удалить "{{ recipe.title }}"?</title>{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Удалить">
</form>
{% endblock %}

pasta/recipes/templates/recipes/recipe_detail.html
{% extends "base_generic.html" %}

{% block title %}<title>Паста | {{ recipe.title }}</title>{% endblock %}

{% block content %}
<div class="recipe-detail">
    {% if recipe.author == request.user %}
    <div class="author-panel">
        <a href="{% url 'recipe-publish' recipe.slug %}" class="publish-button{% if not recipe.is_published %} to-publish{% endif %}">{% if recipe.is_published %}Снять с публикации{% else %}Опубликовать{% endif %}</a>
        <a href="{% url 'recipe-edit' recipe.slug %}" class="edit-button">Редактировать</a>
        <a href="{% url 'recipe-remove' recipe.slug %}" class="remove-button">Удалить</a>
    </div>
    {% endif %}

    <div class="info-block">
        <div class="cover-wrapper">
            <img src="{{ recipe.image.url }}" width="250" height="250">
        </div>
        <div class="author unselectable">
            <div class="author-label">
                <span class="line"></span>
                <span id="label">Автор</span>
                <span class="line"></span>
            </div>
            {% include './includes/author_label.html' with instance=recipe %}
        </div>
        <div class="menu-cuisine unselectable">{{ recipe.menu.name }} &#8226; {{ recipe.cuisine.name }}</div>
        {% if not recipe.is_published %}
        {% include './includes/draft_label.html' %}
        {% endif %}
        <div class="creation-date unselectable">{{ recipe.creation_date|date:"d.m.Y" }}</div>
        <div class="title">{{ recipe.title }}</div>
        <div class="cooking-time unselectable">{% include './includes/cooking_time.html' with instance=recipe %}</div>
        <div class="favorite unselectable">
            {% include './includes/favorite_form.html' with instance=recipe %}
        </div>
        <div class="description">{{ recipe.description | safe | linebreaks }}</div>
    </div>

    <div class="ingredients-list">
        <span class="subtitle">Ингредиенты</span>
        <ul>
            {% for ingredient in recipe.recipeingredient_set.all %}
            <li>
                <span class="ingredient">
                    <a href="{% url 'ingredient-detail' group_slug=ingredient.ingredient.group.slug slug=ingredient.ingredient.slug %}">{{ ingredient.ingredient.name }}</a>
                </span>
                <span class="line"></span>
                <span class="amount">{% if ingredient.amount %}{{ ingredient.amount }} {% endif %}{{ ingredient.unit.name }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="steps-list">
        <span class="subtitle">Пошаговый рецепт</span>
        <div class="steps-wrapper">
        {% for step in recipe.recipestep_set.all %}
            <div class="step">
                <div class="cover-wrapper">
                    <img src="{{ step.image.url }}" width="100" height="100">
                </div>
                <span>{{ step.description | safe | linebreaks }}</span>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block footer_scripts %}
{% include './includes/favorite_script.html' %}
{% endblock %}

pasta/recipes/templates/recipes/recipe_form.html
{% extends "base_generic.html" %}

{% block title %}<title>Паста | Добавить рецепт</title>{% endblock %}

{% block header_scripts %}
{{ ingredient_formset.media.css }}
{% endblock %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data" class="recipe-form">
    {% csrf_token %}
    {{ recipe_form.author.as_hidden }}
    {{ recipe_form.slug.as_hidden }}

    <div class="form-block" id="rcp">
        <div class="items-wrapper" id="cvr-wrapper">
            <div class="block-items" id="img-item">
                <div class="cover-wrapper">
                    {% if recipe_form.instance.image %}
                    <img src="{{ recipe_form.instance.image.url }}" width="200" height="200">
                    {% else %}
                    {% include './includes/default_recipe_img.html' %}
                    {% endif %}
                </div>
                {{ recipe_form.image }}
                {{ recipe_form.image.errors }}
            </div>
        </div>
        <div class="items-wrapper" id="othr-wrapper">
            <div class="block-items" id="title-item">
                {% comment %}{{ recipe_form.title.label_tag }}{% endcomment %}
                {{ recipe_form.title }}
                {{ recipe_form.title.errors }}
            </div>
            <div class="block-items" id="cuisine-item">
                {{ recipe_form.cuisine.label_tag }}
                {{ recipe_form.cuisine }}
                {{ recipe_form.cuisine.errors }}
            </div>
            <div class="block-items" id="menu-item">
                {{ recipe_form.menu.label_tag }}
                {{ recipe_form.menu }}
                {{ recipe_form.menu.errors }}
            </div>
            <div class="block-items" id="ct-item">
                {{ recipe_form.cooking_time.label_tag }}
                {{ recipe_form.cooking_time }}
                {{ recipe_form.cooking_time.errors }}
            </div>
            <div class="block-items" id="desc-item">
                {{ recipe_form.description }}
                {{ recipe_form.description.errors }}
            </div>
        </div>
    </div>
    
    <div class="form-block" id="ing-block">
        <h3>Ингредиенты</h3>
        {% for error in ingredient_formset.non_form_errors %}
        <span class="errors">{{ error }}</span>
        {% endfor %}
        <div class="block-items" id="ing-items">
            {% for form in ingredient_formset %}
            <div class="ingredient removable-item" {% if form.DELETE.value %}hidden="hidden"{% endif %}>
                {{ form.id }}
                {{ form.ingredient }}
                {{ form.amount }}
                {{ form.unit }}
                {{ form.DELETE.as_hidden }}
                <i class="fa fa-times delete-form" aria-hidden="true"></i>
                {% if form.errors %}
                <span class="errors">Заполните поля или удалите их.</span>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {{ ingredient_formset.management_form }}
        <span class="btn btn-success btn-sm" id="add-ing-btn">Добавить ингредиент</span>
    </div>

    <div class="form-block" id="stp-block">
        <h3>Шаги</h3>
        {% for error in step_formset.non_form_errors %}
        <span class="errors">{{ error }}</span>
        {% endfor %}
        <div class="block-items" id="stp-items">
            {% for form in step_formset %}
            <div class="step removable-item" {% if form.DELETE.value %}hidden="hidden"{% endif %}>
                {{ form.id }}
                <div class="img-wrapper">
                    <div class="cover-wrapper">
                        {% if form.instance.image %}
                        <img src="{{ form.instance.image.url }}">
                        {% else %}
                        {% include './includes/default_step_img.html' %}
                        {% endif %}
                    </div>
                    {{ form.image }}
                </div>
                <div class="othr-wrapper">
                    {{ form.description }}
                    {{ form.DELETE.as_hidden }}
                    <span class="btn btn-danger btn-sm delete-form">Удалить</span>
                    {% if form.errors %}
                    <span class="errors">Заполните поля или удалите их.</span>
                {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        {{ step_formset.management_form }}
        <span class="btn btn-success btn-sm" id="add-stp-btn">Добавить шаг</span>
    </div>

    <div class="form-block" id="btns-block">
        <input type="submit" name="submit-save" value="Сохранить" class="btn btn-secondary">
        <input type="submit" name="submit-publish" value="Опубликовать" class="btn btn-primary">
    </div>

</form>
{% endblock %}

{% block footer_scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
{{ ingredient_formset.media.js }}
<script>
var ingredient_form_count = {{ ingredient_formset.total_form_count }};
var step_form_count = {{ step_formset.total_form_count }};

$('#add-ing-btn').click(function() {
    if ({{ ingredient_formset.absolute_max }} > ingredient_form_count) {
        var new_form = (
            '<div class="ingredient removable-item">' +
            '{{ ingredient_formset.empty_form.ingredient|escapejs }} ' +
            '{{ ingredient_formset.empty_form.amount|escapejs }} ' +
            '{{ ingredient_formset.empty_form.unit|escapejs }} ' +
            '{{ ingredient_formset.empty_form.DELETE.as_hidden|escapejs }} ' +
            '<i class="fa fa-times delete-form" aria-hidden="true"></i>' +
            '</div>'
        ).replace(/__prefix__/g, ingredient_form_count);
        $('#ing-items').append(new_form);
        ingredient_form_count++;
        $('#id_ingredient-TOTAL_FORMS').val(ingredient_form_count);
    };
});

$('#add-stp-btn').click(function() {
    if ({{ step_formset.absolute_max }} > step_form_count) {
        var new_form = (
            '<div class="step removable-item">' +
            '   <div class="img-wrapper">' +
            '       <div class="cover-wrapper">' +
            '           {% include "./includes/default_step_img.html" %}' +
            '       </div>' +
            '       {{ step_formset.empty_form.image|escapejs }}' +
            '   </div>' +
            '   <div class="othr-wrapper">' +
            '       {{ step_formset.empty_form.description|escapejs }}' +
            '       {{ step_formset.empty_form.DELETE.as_hidden|escapejs }}' +
            '       <span class="btn btn-danger btn-sm delete-form">Удалить</span>' +
            '   </div>' +
            '</div>'
        ).replace(/__prefix__/g, step_form_count);
        $('#stp-items').append(new_form);
        step_form_count++;
        $('#id_step-TOTAL_FORMS').val(step_form_count);
    };
});

$('#ing-items, #stp-items').on('click', '.delete-form', function(){
    let parrentDiv = $(this).closest('div.removable-item');
    parrentDiv.find('input[id*="DELETE"]:hidden').attr('value', 'on');
    parrentDiv.attr('hidden', true);
});

</script>
{% endblock %}

pasta/recipes/templates/recipes/recipe_list.html
{% extends "base_generic.html" %}

{% block title %}<title>Паста | Список рецептов</title>{% endblock %}
{% block content %}
{% block sidebar %}{% endblock %}
{% block navigation_button %}{% endblock %}
<div class="filter-form">
    <form action="" method="get">
        {{ form }}
        {% block add_filter_fields %}{% endblock add_filter_fields %}
        <input type="submit" value="Показать" class="btn btn-primary btn-sm">
    </form>
</div>
{% block search_info %}{% endblock %}
{% for recipe in recipe_list %}
{% include './includes/recipe_preview_block.html' with instance=recipe %}
{% empty %}
<h3>Не найдено ни одного рецепта</h3>
{% endfor %}
{% endblock %}
{% block footer_scripts %}
{% include './includes/favorite_script.html' %}
{% endblock %}